### ISSUE TITLE
px-login: Console error user-info-sample.json Failed to load resource (P2)

### ISSUE THREAD

**Issue by Aileen-H** [predix-ui/predix-ui.github.io#145]
Error in Console 
https://www.predix-ui.com/px-login/user-info-sample.json Failed to load resource: the server responded with a status of 404 ()

Browser: Issue seen in Safari 10 and Chrome

**Comment by ppeyro** [comment]
Attaching a screenshot:

![screen shot 2017-08-01 at 1 55 41 pm](https://user-images.githubusercontent.com/10835611/28847039-a1fc96a8-76c2-11e7-93e3-b11421c0f3dd.png)


Also, noting that in the codepen, there is an object error messages most likely due to the same failure.

Here's a screenshot of the codepen.
![screen shot 2017-08-01 at 2 05 42 pm](https://user-images.githubusercontent.com/10835611/28847059-bb9ac90e-76c2-11e7-8552-482ce0686f88.png)

**Comment by randyaskin** [comment]
Fixed incorrect url in demo page. It relies on iron-ajax, so I don't think we'll ever be able to get the CodePen to actually simulate a login.
