### ISSUE TITLE
icon: codepen fails.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#148]
Getting a 500 from px-icon.html on codepen open.

## Screenshot:
![screen shot 2017-08-01 at 12 30 39 pm](https://user-images.githubusercontent.com/10835611/28843283-6ffe0504-76b5-11e7-98a0-4865f7686703.png)

**Comment by randyaskin** [comment]
I fixed the CodePen in v2.0.4 so that it includes the two imports it needs (`px-icon-set/px-icon-set.html` and `px-icon-set/px-icon.html`). There is still an erroneous import that doesn't really exist and isn't needed (`px-icon/px-icon.html`) but eliminating this would require building a lot of exception logic into px-demo-snippet, since this is only our second repo (along with px-tabs) that follows a non-standard naming and import convention. Might also be able to avoid this mess by forcing px-icon-set to import px-icon for us? ¯\_(ツ)_/¯
