### ISSUE TITLE
Explore running hydrolysis and generating API description object at buildtime

### ISSUE THREAD

**Issue by mdwragg** [predix-ui/predix-ui.github.io#22]
As we discussed, there may be an opportunity to analyse the component at build time, store away the resultant JSON in the GH pages branch and use that as input to the API viewer when the page is accessed.

This has the following advantages:

- we don't have to ship/parse/use hydrolysis on the client.
- service worker can cache the resultant json object describing the API.
- others?

**Comment by runn-vermel** [comment]
@mdwragg 

After spiking on this, I can't recommend doing this.

Because of the circular nature of the object generated by hydrolysis, we would have to "un-circular" the json by using the npm package "circular-json", save the object somewhere that would have to be downloaded onto the user's machine, then use browserify to include circular-json (and its dependencies) in a form that runs on the user's machine without node/require.

Once the user loads the page, we now have to "re-circular" the object using the browserify plugin, and have iron-doc-viewer read the final result. This is the action that's most expensive in terms of time - I believe it'll take as long as hydrolysis does to analyze the files.

The cost for all of this would be as bad as keeping what we have right now, so, as good of an idea this seemed initially, sadly there's no way to actually do this in an "easy, small cost to user" way.

**Comment by benoitjchevalier** [comment]
Is it worth re-spiking it using polymer analyzer? They aim at replacing hydrolysis with it, not sure if it  gives you a "less circular" result though... my 2 ct

**Comment by runn-vermel** [comment]
i'll check if the resulting object isn't circular as well.

**Comment by mdwragg** [comment]
Thanks for the analysis @runn-vermel.
