### ISSUE TITLE
Mismatched number of issues on demo page vs. actual in the corresponding repo

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#54]
More of a question, but wondering why some components show having issues but there are none in their corresponding repo?

I haven't done an exhaustive search, but just couple of examples below:

![screen shot 2017-05-11 at 3 50 38 pm](https://cloud.githubusercontent.com/assets/10835611/25975302/5b68740a-3662-11e7-9368-b77027f4f4af.png)

![screen shot 2017-05-11 at 3 51 55 pm](https://cloud.githubusercontent.com/assets/10835611/25975304/61323920-3662-11e7-8fe3-3dfb5eea2a0a.png)

**Comment by randyaskin** [comment]
It would appear we're using a slightly incorrect URL for our shields.io images.

Compare:
https://img.shields.io/github/issues/PredixDev/px-data-table/master.svg?style=flat-square
https://img.shields.io/github/issues/PredixDev/px-data-table.svg?style=flat-square

Also note that the total count is the sum of both the Issues and Pull Requests tabs, since PRs are just a specific kind of issue. I've updated the url in px-demo, it should get picked up by each demo page as they rebuild over time (probably not high enough priority to rebuild them all at once).
