### ISSUE TITLE
breadcrumbs: Warning on page load, duplicate elements.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#88]
![screen shot 2017-07-28 at 6 29 09 pm](https://user-images.githubusercontent.com/10835611/28741035-d066375e-73c2-11e7-9b8f-62ef32d71fc4.png)

**Comment by mdwragg** [comment]
@davidrleonard - I took this presuming it was HTML import path mismatch (meaning it got loaded twice from two "different" places). I was wrong... Any idea what this might be?

**Comment by davidrleonard** [comment]
@mdwragg I'll look.

**Comment by davidrleonard** [comment]
I see the issue is coming out of Hydrolysis. It's seeing a `class Thing { }` that isn't actually a custom element but trying to parse it anyway. We have two options to fix:

1. We can switch to the new Analyzer (which I think we want to do at some point anyway) which doesn't choke on ES6 code like this
2. We can use `polymer build` and bundle this/all demos so it tranforms down to ES5 and the analyzer skips over it.

We'll need to do something like this anyway as we switch to full hybrid/2.0 support, as we'll be forced to publish our elements with class syntax vs. `Polymer({})` factory syntax.

For right now, this throws some junk into the console but does not fail the demo. It will potentially fail the demo for other reasons in IE11/non-ES6 compatible browsers — the root cause is ES6 code that will introduce bugs in those browsers.
