### ISSUE TITLE
IE11: Clipboard demo issues

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#96]
IE11 specific:

In Copy & Cut tab:

- Input field is cut off and the placeholder text is not rendering.
- If you try to enter text and copy it by selecting the Copy icon,  it works and it can be pasted.  However, the pasted text contains the mishmash of the placeholder text and the text you attempted to copy.

In Copy String tab:

- Text alignment is off and overlays the icon.

In Properties:

- Copy From And Data Clipboard Text don't seem to be doing anything? Can't copy from that field or clip anything?  Unclear Usage?

### Comparing IE11 to Chrome/ Copy tab
![screen shot 2017-07-31 at 11 48 14 am](https://user-images.githubusercontent.com/10835611/28793088-b38a2a0c-75e6-11e7-9227-6eac0839c784.png)

### Copy String Tab

![2017-07-31_1156](https://user-images.githubusercontent.com/10835611/28793359-9a1d4c92-75e7-11e7-9a11-f9c6d5ded014.png)

**Comment by randyaskin** [comment]
Fixed alignment issues in IE.

The "copy from" property aligns with whatever class/ID you have on the input field you want to copy from. I've removed from the demo since it's confusing. The "data clipboard text" field is used by the 3rd demo/tab, where you're passing the string into the component as a property rather than pulling it out of a field or something.
